### ISSUE TITLE
cb-exit

### ISSUE THREAD

**Issue by computermouth** [CBPP/cbpp#12]
At first, the python script seems to be fully functional. However, if you logout(seems to always work), then suspend(also seems to work), then try either rebooting or powering off, it will show the proper output, but never perform the action.

**Comment by nfultz** [comment]
I seem to recall this being a PAM problem... Will check notes later.

**Comment by computermouth** [comment]
Found some goodies here: http://www.freedesktop.org/software/systemd/man/systemctl.html. I won't be able to check/commit them until tomorrow. The package still needs to get moved to it's own repo anyways. But if anyone would like to give it a shot on the beta install and submit a pull, that'd be cool.

**Comment by computermouth** [comment]
Changed the options to take systemctl commands, the issue persists.

**Comment by ghost** [comment]
The issue is that the logout action actualy don't destoy the whole session of the user. Some applications are still running in the background and loginctl can still see them as in an active user session. 

When we execute the command cbpp-exit in terminal after a logout (with the command pkill -u $USER or openbox --exit) org.freedesktop.logins1.reboot require that we authentify. If the password is enter, the system reboot. When the command is exectued outside a terminal, it would only failed as no password can be enter. Mostly the same thing append when the halt buton is press. Close the session with loginctl kill-user $USER is not currently possible as root priviege is require to use this command, but if use manulay to close the session, the script work with no issue. 

Sadly I don't have an out-of-the-box solution, but I think that the best way to approch this issue is to create a polkit action (or a sudo config) that permit the use of the loginctl by an unpriviege user. An other way would be to upgrade the package. It is possible for the user can close is own session in systemd 219. jessie is currently in 215 but debian experimental package is at 219. It would be possible to use this package, but it's difficult to foresee all the problem this upgrade would cause.

I hope this help in the resolution of the problem. I will continu my effort to find a elegant solution to this problem.

**Comment by ghost** [comment]
I've propose a fix in the cbpp-exit. This basicly tell systemd to close all of the user process when the session is close by openbox --exit. This should solve the cbpp-exit issue.

**Comment by computermouth** [comment]
The issue has been fixed with a change to the slim package to launch polkit immediately after login.

**Comment by ghost** [comment]
Nice ! 
And the infamous cbpp-exit bug is resoved !
