### ISSUE TITLE
64-bit - what do we need?

### ISSUE THREAD

**Issue by idvoretskyi** [CBPP/cbpp#21]
What're the reasons of unavailability 64-bit version of CBPP? How does the community may help to build this version?

**Comment by computermouth** [comment]
Specifically, ...none really. I hadn't expected as much attention as the project received. All the packages that have been rebuilt so far are platform independent. As such, all that needs to take place is the build process on a 64-bit machine. I haven't done it yet because the Beta was not intended to be a permanently used release. I'll likely be generating 64-bit images for every future release. 64-bit and EFI support are the big pressing issues outside of the package modifications, but with what research I've done so far, it seems like it will be a trivial amount of work.

**Comment by idvoretskyi** [comment]
Do you need any kind of support in releasing 64-bit version also? If you need, I may help you in that.

**Comment by computermouth** [comment]
Honestly, it should be about a 15 minute job to test it and make sure it works. I'd suggest trying that, but currently we've only distributed the packages from the i386 build. So unfortunately for the time being, I believe we'll just have to wait. Thanks for the offer though!
