### ISSUE TITLE
Fresh CB++ install - problem with NetWorkManager applet - wifi

### ISSUE THREAD

**Issue by mentorj** [CBPP/cbpp#26]
Hi all,
thanks for the awesome job -)
I just installed CB++ on my laptop...The installation is quite perfect...
Everything works excepted a problem with network-manager applet & my wifi card (IWL compatible one) , my laptop is a Thinkpad X230 ...The card is well detected (after installing the iwlwifi firmware package), shown in the wifi networks list (all ESSID are present) but clicking on any ESSID to trigger authentication popup frame does nothing!!! I don't know where to look for traces or debug messages...
I just installed wicd & its gui and I can connect to my network with my wifi chipset...
Sounds to be a bug isn't it ?

excerpt from dmesg:
[    2.953532] iwlwifi 0000:03:00.0: firmware: direct-loading firmware iwlwifi-2
000-6.ucode
[    2.953701] iwlwifi 0000:03:00.0: loaded firmware version 18.168.6.1 op_mode 
iwldvm
[    2.973482] iwlwifi 0000:03:00.0: CONFIG_IWLWIFI_DEBUG disabled
[    2.973485] iwlwifi 0000:03:00.0: CONFIG_IWLWIFI_DEBUGFS disabled
[    2.973487] iwlwifi 0000:03:00.0: CONFIG_IWLWIFI_DEVICE_TRACING disabled
[    2.973489] iwlwifi 0000:03:00.0: Detected Intel(R) Centrino(R) Wireless-N 22
00 BGN, REV=0x104
[    2.973662] iwlwifi 0000:03:00.0: L1 Enabled - LTR Disabled
[    4.453261] iwlwifi 0000:03:00.0: L1 Enabled - LTR Disabled

lshw -C network:
 *-network
       description: Wireless interface
       product: Centrino Wireless-N 2200
       vendor: Intel Corporation
       physical id: 0
       bus info: pci@0000:03:00.0
       logical name: wlan0
       version: c4
       serial: 9c:4e:36:bf:9b:9c
       width: 64 bits
       clock: 33MHz
       capabilities: bus_master cap_list ethernet physical wireless
       configuration: broadcast=yes driver=iwlwifi driverversion=3.16.0-4-686-pae firmware=18.168.6.1 latency=0 link=no multicast=yes wireless=IEEE 802.11bgn
       resources: irq:45 memory:f1c00000-f1c01fff

I use the standard 3.16-PAE kernel because I have 16Gb on this laptop and don't want to use only 3.5Gb....

Regards

**Comment by computermouth** [comment]
Oh interesting! We've made a lot of improvements since the Beta, so this very well may have been fixed by now.

Try 'apt-get install gnome-keyring'.

If a wipe is out of the question, believe it or not, a theme change might help! You could try apt-getting a theme pack like murrine-themes and changing it in lxappearance.

If you like, you could try one of our more recent daily 64-bit images, which aren't public at the moment, so you'd get a sneak peek at our near-finished release. You may get an error about updating databases during the install with it though, don't worry, it's harmless. Here's a download link:
https://drive.google.com/file/d/0Bwj01JIKs-44NTFQT2FzYjJwdE0/view?usp=sharing
(sorry about the Gdrive link, I don't want to punish our server bandwidth)

**Comment by mentorj** [comment]
Hi Ben,
thanks for the answer....
I am surprised ..How theming could have impacts on the network manager ?
But indeed you are right, I followed your advice and installed murrine ...It does not work but now clicking on my ESSID gives me back an alert box with :failed to activate connection no session found for uid 1000 (unknown) ...Strange because 1000 is the id of my current profile!!!
I would like to avoid wiping out but.....

The 64 bit image is not ready yet ?

Thanks for your support

**Comment by mentorj** [comment]
Thanks for the link Ben...Who cares about using the Google infrastructure & bandwidth ? -)

**Comment by mentorj** [comment]
Hi ben,
I wiped out my installation and installed the iso linked in your previous answer.
Very bad idea!!! It seems that this image is broken, The process (made 2 times) goes till the grub  update (it works) and after the screen turns black , logs say that the installer process will be restarted but it is not....I tried to reboot but I am unable to log in the  system (in console or graphically) so I guess that the user account has not been created yet...I made the install one time in graphic mode and one time in console , both methods induce the same result...
I am using my kids PC to write the email and I must find a solution quickly to work..

Regards

**Comment by computermouth** [comment]
Oh jeez, sorry about that. It looks like something happened during the upload and broke the .iso. I just tried uploading another, but that image broke during the upload as well.

These are two daily images from last week that I set aside because they installed for me. Ultimately, these are not stable releases, your best option would probably just be using some current stable release (especially for a computer you need for work, as I can't guarantee the stability of our current builds).

**Comment by mentorj** [comment]
Yes I think there 's a problem and having not the target MD5 sum (or SHa1) makes it impossible to check once downloaded. I finished by picking an absolutely unknown distro : Wakawa Openbox Edition.
It's beautiful maybe a little bit huge in disk & memory than CB++ or CB but my machine is quite powerful so saving 100 Mb of RAM is not a big concern.

Thnaks again for the work I may wait a few weeks and a stable 64 bit version to make a new CB++ install..
Best regards

**Comment by computermouth** [comment]
Yeah, can't say I blame you. I had to do a bit of hackery to get the 64-bit build running on my laptop. But stay tuned for the upcoming official release!
