### ISSUE TITLE
Power Management does not have an icon

### ISSUE THREAD

**Issue by danhm** [CBPP/cbpp#30]
mate-power-manager is just a blank space in my taskbar when set to "never display an icon" or "only when low power". However, setting it to "always display" and then one of those two options makes it behave as expected, not taking up space in the taskbar with an icon-sized space.

![screenshot - 06192015 - 11 13 50 am](https://cloud.githubusercontent.com/assets/10888280/8259840/5db39646-1674-11e5-9b5a-731c5ea07007.png)

**Comment by kurgol** [comment]
Probably you have installed mate-power-manager because the default keybind points at mate-power-manager in error (it should be xfce4-power-manager-settings). 

You can probably fix this by just ```apt purge mate-power-manager``` and then configure the keybind correctly (I wrote a blog post today on how to fix this and some other issues https://www.neontribe.co.uk/crunchbangplusplus-9-tweaks/).
