### ISSUE TITLE
on x86 machines, raspberry firmware is being installed by default

### ISSUE THREAD

**Issue by LokiMetaSmith** [CBPP/cbpp#51]
On a fresh ISO install I am running 

sudo apt purge raspi-firmware
sudo rm -rf /etc/kernel/postinst.d/z50-raspi-firmware
sudo rm -rf /etc/initramfs/post-update.d/z50-raspi-firmware

I'm assuming these shouldn't be installed when running on an x86 arch

**Comment by mikaelmantel** [comment]
Same on amd64

**Comment by Kackotopi** [comment]
A easier and faster way would be: **sudo dpkg --purge raspi-firmware**

**Comment by johnraff** [comment]
I wandered onto this page by chance...
The raspberry firmware issue seems to be coming from live-build - the next version of l-b should have it fixed.
We hit the same issue in BunsenLabs; in case it's any help, here: https://forums.bunsenlabs.org/viewtopic.php?pid=128516#p128516

**Comment by computermouth** [comment]
Cool thanks @johnraff. Is this causing issues for anyone, or is it just the fact that it's there and needn't be?

**Comment by johnraff** [comment]
It did cause problems with upgrading the kernel and regenerating initramfs, and there was a lot of discussion on the Debian forums, eg https://forums.debian.net/viewtopic.php?p=777298&sid=6170aba5ab6b18cfee651a7e76869928#p777298

The issue was fixed in Debian live images, and a [commit](https://salsa.debian.org/live-team/live-build/-/commit/8eaf20daf1cf79669975b1acfe4d6fa453eb6307) went into live-build, but the live-build package on Debian still doesn't incorporate that fix. We patched our live-build to incorporate it, but it shouldn't be necessary in the future.

**Comment by computermouth** [comment]
New build's in the works, and should be out shortly, thanks folks!
