### ISSUE TITLE
Replace Waldorf pkgs with newer Jessie pkgs

### ISSUE THREAD

**Issue by nfultz** [CBPP/cbpp#8]
Jessie contains a much newer version of compton, we should use that instead of compton-git. This will need to be fixed in the installer and in the cb metapackage that pulls in compton-git.

**Comment by AlexDaniel** [comment]
And I feel like it is not the only package that has to be dropped from custom debs.
- arandr_0.1.6-1crunchbang1_all.deb but jessie has 0.1.7.1-1
- fbxkb_0.6-1-2crunchbang2_i386.deb but jessie has 0.6-1.1 while 0.6-2 is unstable (worth dropping it, I guess?)
- lxappearance_0.5.1-1crunchbang2_i386.deb but jessie has 0.6.1-1
-  terminator_0.93-4-bzr1026_all.deb but jessie has 0.97-4
- thunar_1.2.3-5~crunchbang1_i386.deb but jessie has 1.6.3-2. This one IS VERY IMPORTANT because thunar 1.2.3 does not even have tabs.
- viewnior_1.3-2~crunchbang_i386.deb but jessie has 1.4-2+b1
- xdotool_2.20110530.1-3_i386.deb but jessie has 1:3.20140805.1-2

This list is incomplete, of course.

**Comment by computermouth** [comment]
My apologies, some of the packages are remnants of when I just downloaded all of the packages from the repo. While the Beta disc currently has the newest version of these packages, you're right, there's no reason for them to be here.

**Comment by computermouth** [comment]
The old packages were originally included in case there were any #! specific config files in them. I'm going through the packages now (primarily with the ones that don't contain "crunchbang") and testing the build after each batch removal.

**Comment by computermouth** [comment]
This has been largely finished. I'm still looking at slim, we might have to start of with a modified version to make sure that the default theme gets in there without getting overwritten during the netinstall.
